<?php
// +----------------------------------------------------------------
// | IAIO [ I'm ALL IN ONE ]
// +----------------------------------------------------------------
// | Powered by http://www.iaio.cn
// +----------------------------------------------------------------
// | Author: 油腻大叔 <gephene@gmail.com>
// +----------------------------------------------------------------


namespace iaio;

use think\Controller;

class Aio extends Controller
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


}